# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0047_merge'),
        ('tasks', '0037_auto_20160105_0720'),
        ('tasks', '0045_auto_20151228_1340'),
    ]

    operations = [
    ]
