# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0053_auto_20160113_1018'),
    ]

    operations = [
    ]
