# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0054_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='frozen',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
