# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20160105_0720'),
        ('users', '0022_auto_20151220_1433'),
    ]

    operations = [
    ]
