# encoding: utf-8
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator

gt_zero = MinValueValidator(0)
lt_three = MaxValueValidator(3)


# image_validator=RegexValidator(regex='^/image/\d+/\d+\.(jpg|jpeg|png)$')

class StoreCreateForm(forms.Form):
    platform = forms.IntegerField()
    name = forms.CharField(max_length=255)
    user_id = forms.IntegerField()
    url = forms.URLField(max_length=255)
    wangwang = forms.CharField(max_length=255)
    address = forms.CharField(max_length=255)
    buy_time_limit = forms.IntegerField()


class TaskCreateForm(forms.Form):
    id = forms.IntegerField(required=False, )
    platform = forms.IntegerField()
    store_id = forms.IntegerField()
    task_type = forms.IntegerField()
    return_type = forms.IntegerField(required=False, )
    # 商品
    commodity_total = forms.IntegerField(validators=[gt_zero, lt_three])
    commodity_num1 = forms.IntegerField(validators=[gt_zero, ])
    commodity_name1 = forms.CharField()
    commodity_url1 = forms.URLField()
    commodity_pic_path1 = forms.CharField()
    commodity_unitprice1 = forms.DecimalField(max_digits=9, decimal_places=2, validators=[gt_zero, ])
    commodity_displayprice1 = forms.DecimalField(max_digits=9, decimal_places=2, validators=[gt_zero, ])
    commodity_num2 = forms.IntegerField(required=False, validators=[gt_zero, ])
    commodity_name2 = forms.CharField(required=False, )
    commodity_url2 = forms.URLField(required=False, )
    commodity_pic_path2 = forms.CharField(required=False)
    commodity_unitprice2 = forms.DecimalField(max_digits=9, decimal_places=2, required=False, validators=[gt_zero, ])
    commodity_displayprice2 = forms.DecimalField(max_digits=9, decimal_places=2, required=False, validators=[gt_zero, ])
    commodity_num3 = forms.IntegerField(required=False, validators=[gt_zero, ])
    commodity_name3 = forms.CharField(required=False, )
    commodity_url3 = forms.URLField(required=False, )
    commodity_pic_path3 = forms.CharField(required=False)
    commodity_unitprice3 = forms.DecimalField(max_digits=9, decimal_places=2, required=False, validators=[gt_zero, ])
    commodity_displayprice3 = forms.DecimalField(max_digits=9, decimal_places=2, required=False, validators=[gt_zero, ])
    #
    # free_postage = forms.BooleanField()
    low_price = forms.DecimalField(max_digits=9, decimal_places=2, required=False)
    up_price = forms.DecimalField(max_digits=9, decimal_places=2, required=False)
    commodity_address = forms.CharField(max_length=255, required=False)
    publish_start_date = forms.DateField(required=False)
    publish_start_time = forms.TimeField(required=False)
    publish_end_time = forms.TimeField(required=False)
    publish_num = forms.IntegerField(required=False)
    publish_total = forms.IntegerField(required=False)
    bonus = forms.DecimalField(max_digits=9, decimal_places=2, required=False)
    task_remark = forms.CharField(required=False)
    order_comment = forms.CharField(required=False, max_length=255)
    # 搜索关键词
    search_entry_total = forms.IntegerField(validators=[gt_zero, lt_three], required=False)
    search_entry_keyword1 = forms.CharField(required=False)
    search_entry_sort1 = forms.IntegerField(required=False)
    search_entry_pay_num1 = forms.IntegerField(required=False)
    search_entry_order_total1 = forms.IntegerField(validators=[gt_zero, ], required=False)
    search_entry_flow_total1 = forms.IntegerField(validators=[gt_zero, ], required=False)
    search_entry_collect_total1 = forms.IntegerField(validators=[gt_zero, ], required=False)
    search_entry_keyword2 = forms.CharField(required=False)
    search_entry_sort2 = forms.IntegerField(required=False)
    search_entry_pay_num2 = forms.IntegerField(required=False)
    search_entry_order_total2 = forms.IntegerField(required=False, validators=[gt_zero, ])
    search_entry_flow_total2 = forms.IntegerField(required=False, validators=[gt_zero, ])
    search_entry_collect_total2 = forms.IntegerField(validators=[gt_zero, ], required=False)
    search_entry_keyword3 = forms.CharField(required=False)
    search_entry_sort3 = forms.IntegerField(required=False)
    search_entry_pay_num3 = forms.IntegerField(required=False)
    search_entry_order_total3 = forms.IntegerField(required=False, validators=[gt_zero, ])
    search_entry_flow_total3 = forms.IntegerField(required=False, validators=[gt_zero, ])
    search_entry_collect_total3 = forms.IntegerField(validators=[gt_zero, ], required=False)
    # 订单类型
    order_type_order_total0 = forms.IntegerField(validators=[gt_zero, ])
    order_type_order_total1 = forms.IntegerField(validators=[gt_zero, ])
    order_type_order_total2 = forms.IntegerField(validators=[gt_zero, ])
    order_type_order_total3 = forms.IntegerField(validators=[gt_zero, ])
    order_type_order_total4 = forms.IntegerField(validators=[gt_zero, ])
    order_type_order_total5 = forms.IntegerField(validators=[gt_zero, ])
    order_type_order_total6 = forms.IntegerField(validators=[gt_zero, ])
    comment_keyword = forms.CharField(required=False)
    comment_image = forms.CharField(required=False)
    special_code = forms.CharField(required=False)
    special_pics = forms.CharField(required=False)
    prepublish = forms.BooleanField(required=False)
    step_interval = forms.CharField(required=False)
    # 旺旺条件
    tb_register_time = forms.IntegerField(required=False)
    tb_gender = forms.IntegerField(required=False)
    tb_age = forms.IntegerField(required=False)
    tb_is_credit_card_open = forms.IntegerField(required=False)
    tb_wangwang_level = forms.IntegerField(required=False)
    tb_is_huabei_open = forms.IntegerField(required=False)
    tb_is_talk = forms.IntegerField(required=False)

    is_qian = forms.IntegerField(required=False)

    # 千人千面第一步搜索条件
    qian_keyword1 = forms.CharField(required=False)
    qian_keyword2 = forms.CharField(required=False)
    qian_keyword3 = forms.CharField(required=False)
    qian_keyword4 = forms.CharField(required=False)
    qian_keyword5 = forms.CharField(required=False)
    qian_keyword6 = forms.CharField(required=False)
